// Generated by gencpp from file beginner_tutorials/greating.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GREATING_H
#define BEGINNER_TUTORIALS_MESSAGE_GREATING_H

#include <ros/service_traits.h>


#include <beginner_tutorials/greatingRequest.h>
#include <beginner_tutorials/greatingResponse.h>


namespace beginner_tutorials
{

struct greating
{

typedef greatingRequest Request;
typedef greatingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct greating
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::greating > {
  static const char* value()
  {
    return "6743e6c347f9c39f0a25ef9d7fce858a";
  }

  static const char* value(const ::beginner_tutorials::greating&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::greating > {
  static const char* value()
  {
    return "beginner_tutorials/greating";
  }

  static const char* value(const ::beginner_tutorials::greating&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::greatingRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::greating > 
template<>
struct MD5Sum< ::beginner_tutorials::greatingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::greating >::value();
  }
  static const char* value(const ::beginner_tutorials::greatingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::greatingRequest> should match 
// service_traits::DataType< ::beginner_tutorials::greating > 
template<>
struct DataType< ::beginner_tutorials::greatingRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::greating >::value();
  }
  static const char* value(const ::beginner_tutorials::greatingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::greatingResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::greating > 
template<>
struct MD5Sum< ::beginner_tutorials::greatingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::greating >::value();
  }
  static const char* value(const ::beginner_tutorials::greatingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::greatingResponse> should match 
// service_traits::DataType< ::beginner_tutorials::greating > 
template<>
struct DataType< ::beginner_tutorials::greatingResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::greating >::value();
  }
  static const char* value(const ::beginner_tutorials::greatingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GREATING_H
